### ISSUE TITLE
Horizontal Position of Preview Panel no longer synched

### ISSUE THREAD

**Issue by weiweihuanghuang** [Mark2Mark/Synced-Tabs#11]
Now that in G3 you can freely drag around the horizontal position in the preview panel, this should ideally be synched I think when the plugin is running.

**Comment by Mark2Mark** [comment]
You mean the height of the bottom Preview?

That’s actually not new in G3, what do you mean then?

However, syncing the riszing of the bottom Preview height seems to be broken now, so I’ll see how I can fix that.

**Comment by weiweihuanghuang** [comment]
No I mean how you can drag the horizontal position of whats in the preview panel, like drag it left and right

**Comment by weiweihuanghuang** [comment]
I also noticed the preview panel height doesn't synch, it seems to be 0.5 off when I use similar code

**Comment by Mark2Mark** [comment]
> I also noticed the preview panel height doesn't synch, it seems to be 0.5 off when I use similar code

Yea, that's what I referred to in my previous answer. That worked before but seems broken now. What do you mean by 0.5 off? Off of what?

Thanks for reporting. Didn't know about the horizontal content panning.

**Comment by schriftgestalt** [comment]
The measurement of the preview height sometimes includes then height of the drag separator and sometimes not. So you need to adjust for that in this case.

**Comment by schriftgestalt** [comment]
You should be able to
```
offset = previewView.valueForKey_("selectionOffset")
```
and 
```
previewView.setValue_ForKey_(offset, "selectionOffset")
previewView.setNeedsDisplay_(True)
```

**Comment by weiweihuanghuang** [comment]
> The measurement of the preview height sometimes includes then height of the drag separator and sometimes not. So you need to adjust for that in this case.

So how do we know when to include it or not?

**Comment by weiweihuanghuang** [comment]
> The measurement of the preview height sometimes includes then height of the drag separator and sometimes not. So you need to adjust for that in this case.

How do you find out if this needs to be adjusted for?

**Comment by weiweihuanghuang** [comment]
When I try to run:
`Glyphs.fonts[1].currentTab.previewView.setValue_ForKey_(currentOffset, "selectionOffset")` 
I get this: 
`AttributeError: 'objc.native_selector' object has no attribute 'setValue_ForKey_'`

or if I run:
`Glyphs.fonts[1].currentTab.previewView().setValue_ForKey_(currentOffset, "selectionOffset")`
I get:
`AttributeError: 'NSKVONotifying_GSGlyphsPreview' object has no attribute 'setValue_ForKey_'`

Am I doing this right?

**Comment by schriftgestalt** [comment]
sorry, I mistyped it:
```
Glyphs.fonts[1].currentTab.previewView().setValue_forKey_(currentOffset, "selectionOffset")
```

**Comment by weiweihuanghuang** [comment]
Running this doesn't move the preview offset at all, i.e.

`Glyphs.fonts[0].currentTab.previewView().setValue_forKey_(0, "selectionOffset")`

doesn't change the position either?

**Comment by weiweihuanghuang** [comment]
@schriftgestalt what's the code for getting the horizontal dragging offset in the preview panel (attached, not the window) and synching that?

**Comment by schriftgestalt** [comment]
Can you try this:
```
currentOffset = font.currentTab.previewView().offset()
font.currentTab.previewView().setOffset_(newOffset)
```

**Comment by weiweihuanghuang** [comment]
Thanks I just tried it but it doesn't work

**Comment by weiweihuanghuang** [comment]
setOffset_() doesn't seem to do anything

**Comment by schriftgestalt** [comment]
Sorry for the mess. I had another look and testes it this time:
```
from Foundation import NSPoint, NSValue
currentOffset = Font.currentTab.previewView().valueForKey_("userOffset")
print(currentOffset)
Font.currentTab.previewView().setValue_forKey_(NSValue.valueWithPoint_(NSPoint(-200, 0)), "userOffset")
Font.currentTab.previewView().setNeedsDisplay_(True)
```

**Comment by weiweihuanghuang** [comment]
Thanks Georg!
