### ISSUE TITLE
G3 glyphsPlugin version is not very smooth 

### ISSUE THREAD

**Issue by harbortype** [Mark2Mark/Synced-Tabs#13]
When the plugin syncs the views, it frequently ends up in a different position before going to the correct one. It looks like G3 resets the viewport coordinates first and then sets it again but it can’t do it fast enough. I’m not sure if this is an issue with the plugin or with Glyphs itself (@schriftgestalt @mekkablue). I gave it a shot but couldn’t fix it. 

Here is a screencast. It is very noticeable around the 0:19 mark, when I’m editing the z on one font and the other one flashes the start of the string (abc...).
https://www.dropbox.com/s/cnlqcq331skw1c5/Screen%20Recording%202021-06-11%20at%2010.05.05.mov?dl=0

Glyphs 3.0.3 (3086)

**Comment by Mark2Mark** [comment]
I hadn’t used this plugin for a while and now whitness the same thing.

The performance is **horrible** nowadays, for me unusable!

- It only updates the other tab(s) when you move the mouse.
- When I created the plugin, it updated frequently and **very smoothly** ([As seen in the Repo’s readme animated GIF](https://raw.githubusercontent.com/Mark2Mark/Synced-Tabs/master/Images/SyncedTabs_Gintronic_MarkFroemberg.gif))
- when Zooming, the other file **flickers** as seen in the video.

Something in Glyphs (3) must have changed. @schriftgestalt @mekkablue could you please have a look? You might know better what you changed, that could cause it.


_Please note: the `glyphsPlugin` seems the recent version, Rainer pushed that a few years ago and has set it as the default. I started it as the `glyphsReporter` back then and never had the time to make a proper check of what functionalities where actually copied (or broken)._


https://github.com/Mark2Mark/Synced-Tabs/assets/5824595/9ca166ce-aeca-4011-b57a-08bb10f6bcd8

**Comment by schriftgestalt** [comment]
Using the mouseMove as a trigger is super bad. I had a look a the code and this should be removed.

**Comment by schriftgestalt** [comment]
I cleaned up the code and hopefully made it not spin the CPU/fans any more. It doesn’t sync the pan/zoom any more. We need to find a better way to trigger the sync.

**Comment by schriftgestalt** [comment]
I added a new notification (similar to `UPDATEINTERFACE`) to cover this.
